name: 'ECS Wait'
author: 'Sudheer Akula'
description: 'Waits for ECS service stability'
inputs:
  ecs-cluster:
    description: 'The ECS cluster name (string)'
    required: true
  ecs-services:
    description: 'List of ECS services to wait for (string[])'
    required: true
  retries:
    description: 'How many times to retry the 10 minute wait (integer)'
    default: 2
  aws-region:
    description: 'The AWS_REGION (string)'
  verbose:
    description: 'Whether to print the retry log (bool)'
    default: false
  role-to-assume:
    description: role which has permission to interact with the account
    required: true
outputs:
  retries:
    description: 'How many retries happened until success (integer)'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'clock'
  color: 'purple'
